### PR TITLE
Make Shed a lv1 evo of Ninjask

### PR DESCRIPTION
**Pull request by apple096**

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Shouldn't it be a level 1 evolution of `Nincada`?
image

**Comment by apple096** [comment]
Ninjask, as Nincada evolves into BOTH Pokemon at once

**Comment by apple096** [comment]
Makes it look like Nincada is evolving into both

**Comment by RedSparr0w** [comment]
It does evolve into both though doesn't it?
It should only evolve once per breeding cycle. 🤔

**Comment by apple096** [comment]
Yeah, but making it evolve into both is not exactly possible in the game right now

**Comment by RedSparr0w** [comment]
It should be possible, tyrougue is the same sort of thing, should just select a random evolution if there is multiple.

**Comment by apple096** [comment]
The evo is parallel here though

**Comment by apple096** [comment]
Making shed a lv1 evo of Ninjask may makes it look like the evo is simultaneous

**Comment by RedSparr0w** [comment]
Not sure what you mean by it makes it look simultaneous?

**Comment by apple096** [comment]
So, assume it works the way I think it works, when Nincada evolves into Ninjask, because Ninjask is already Lv1, it evolves into Shedinja, which looks like 2 Pokemons from 1 evolution

**Comment by RedSparr0w** [comment]
Oh, I think I see what you mean now, you want them to both appear at the same time?

**Comment by apple096** [comment]
Yep

**Comment by RedSparr0w** [comment]
Have you tested that it will actually work like that?

**Comment by apple096** [comment]
Tbh, I don't really know

**Comment by RedSparr0w** [comment]
Closed via 20752f59ac82954231aae157160e7b6b94b3aea0
Made it an evolution of Nincada at level 20.
You will obtain both at the same time.
_(it looks like the random level evolution code was removed, may need to be reworked in the future)_

**Pull request closed without merging**
