### PR TITLE
Map

### PR DESCRIPTION
**Pull request by apple096**

### CODE REVIEW

**Review by RedSparr0w — CHANGES_REQUESTED** [review]
A few changes needed:

The routes seem to be missing all the inner corners:
image

Some of the ocean tiles still have the dark border:
image

Missing some land edges, and a lot of missing land corners:
image
image

Pokecenters should be to the left of the routes when possible:
image

This one needs to be inline or above the route area, and maybe move the lake a little closer:
image

Routes should continue under the town:
image

Not sure which route this town is a part of:
Will either need to be moved over and move the dungeon up so the route numbers are visible
Or move the town to the above route and move the dungeon to the end of the route so the end is covered
image

Not sure if these were intentional:
image

Move this onto the route a bit more:
image

Shrink surrounding area, or enlarge the dungeon, and move the entrance to the left:
image

This route should be straight and the town on the route:
image

Maybe make the lake bigger, or just move the town over slightly.
Make the route connect to the town and under:
image

Probably just remove this bend, as it doesn't server much purpose:
image

**Comment by apple096** [comment]
Fixed

**Comment by RedSparr0w** [comment]
Could you have another look over the list, not all of the problems have been resolved.

**Comment by RedSparr0w** [comment]
Also the map image should only be 1600 x 960

**Comment by apple096** [comment]
Done

**Pull request merged**
