### PR TITLE
Sinnoh raw data - Gyms, Routes, Dungeons

### PR DESCRIPTION
**Pull request by apple096**
- [x] Dungeons
- [x] Routes
- [x] Gyms
- [x] Progression
- [x] GameConstants stuffs
Credit : Eru, Rishab and Ultima

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Why is this one `do not merge`?
What still needs doing.

**Comment by apple096** [comment]
Gyms and progression (unlocks, unlock requirements, etc....)

**Comment by RedSparr0w** [comment]
Sweet, could you please update the description with a checklist or something so we can keep track of what still needs doing.

**Comment by apple096** [comment]
Ready!

**Comment by RedSparr0w** [comment]
Looks good to me 👍 
Thanks for the PR

Just a note for later:
the following Pokemon are still unobtainable:
image

**Pull request merged**
