### PR TITLE
Add town images

### PR DESCRIPTION
**Pull request by apple096**

### CODE REVIEW

**Comment by apple096** [comment]
Minified and bigger

**Comment by RedSparr0w** [comment]
I think it might be better to get them directly from Bulbapedia or similar, as some of them are still quite small/blurry:
image

It looks like the source you got them from has made them all smaller to be the same width as eachother.

**Comment by apple096** [comment]
They're all from Bulbapedia actually

**Comment by RedSparr0w** [comment]
🤔 Strange, You might have to manually go into the image, As they've definitely got the full quality images available:
<https://bulbapedia.bulbagarden.net/wiki/File:Twinleaf_Town_Pt.png>
<https://bulbapedia.bulbagarden.net/wiki/File:Fight_Area_Pt.png>

**Comment by apple096** [comment]
Images should be all good now

**Review by RedSparr0w — APPROVED** [review]
Looks great!

Thanks 👍

**Pull request merged**
