### PR TITLE
Mega stuffs

### PR DESCRIPTION
**Pull request by apple096**
Mega stuffs and things
(Pic coming soon)
EDIT : Pics done!

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Looking good!

Could you also add the images for the shiny variants too.

The Pokemon will also need to be made slightly smaller as they look quite large in the Pokemon List.

**Comment by apple096** [comment]
96 x 96 is the limit for the sprites
Ran them through https://tinypng.com/  10 times

**Comment by apple096** [comment]
PR should be OK now

**Review by RedSparr0w — APPROVED** [review]
Looks good!

**Pull request merged**
